name: darty
environment:
  sdk: '^2.18.0'
dependencies:
  analyzer: ^5.6.0
  http: ^0.13.5
  intl: ^0.18.1
  json_annotation: ^4.8.0
dev_dependencies:
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
